# Generated by Django 5.0.6 on 2025-07-02 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="federatedtask",
            options={"ordering": ["-id"], "verbose_name": "联邦学习任务"},
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="系统配置的唯一名称",
                        max_length=50,
                        unique=True,
                        verbose_name="配置名称",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="配置的详细说明",
                        null=True,
                        verbose_name="描述",
                    ),
                ),
                (
                    "config_data",
                    models.JSONField(
                        default=dict,
                        help_text="存储联邦学习相关参数的JSON结构",
                        verbose_name="配置内容",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="标记该配置是否为当前生效配置",
                        verbose_name="是否激活",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="配置创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="配置最后一次修改时间",
                        verbose_name="最后更新时间",
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_config_create_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "系统配置",
                "db_table": "system_config",
                "db_table_comment": "系统配置表",
                "ordering": ["-id"],
            },
        ),
    ]
