# Generated by Django 5.0.6 on 2025-07-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0002_alter_federatedtask_options_systemconfig"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemconfig",
            old_name="create_by",
            new_name="created_by",
        ),
    ]
