# Generated by Django 5.0.6 on 2025-07-02 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0003_rename_create_by_systemconfig_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="federatedtask",
            name="create_by",
        ),
        migrations.AddField(
            model_name="federatedtask",
            name="created_by",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="federated_task_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
            preserve_default=False,
        ),
    ]
