# Generated by Django 5.0.6 on 2025-07-03 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0004_remove_federatedtask_create_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="模型名称"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_info_create_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型信息",
                "db_table": "model_info",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="版本号"
                    ),
                ),
                (
                    "model_file",
                    models.FileField(upload_to="models/", verbose_name="模型文件"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "accuracy",
                    models.FloatField(blank=True, null=True, verbose_name="准确率"),
                ),
                (
                    "loss",
                    models.FloatField(blank=True, null=True, verbose_name="损失值"),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="其他指标"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待评估"),
                            ("active", "已激活"),
                            ("archived", "归档"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "is_deployed",
                    models.BooleanField(default=False, verbose_name="是否已部署"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_version_create_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "model_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="learn_management.modelinfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型版本",
                "db_table": "model_version",
                "db_table_comment": "模型版本表",
                "ordering": ["-id"],
                "unique_together": {("model_info", "version")},
            },
        ),
    ]
