# Generated by Django 5.0.6 on 2025-07-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0005_modelinfo_modelversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelversion",
            name="model_file",
            field=models.CharField(max_length=255, verbose_name="模型文件"),
        ),
    ]
