# Generated by Django 5.0.6 on 2025-07-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0006_alter_modelversion_model_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelversion",
            name="version",
            field=models.CharField(max_length=100, verbose_name="版本号"),
        ),
    ]
