# Generated by Django 5.0.6 on 2025-07-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0007_alter_modelversion_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federatedtask",
            name="aggregation_method",
            field=models.CharField(
                choices=[
                    ("fedavg", "联邦平均 (Federated Averaging, FedAvg)"),
                    ("fedavgm", "联邦平均 with Momentum (FedAvgM)"),
                    ("fedadagrad", "联邦 Adagrad (Federated Adagrad)"),
                    ("fedadam", "联邦 Adam (Federated Adam)"),
                    ("fedopt", "联邦优化器 (Federated Optimizer)"),
                    ("fedprox", "联邦近端平均 (Federated Proximal Averaging, FedProx)"),
                    ("fedtrimmedavg", "联邦截尾平均 (Federated Trimmed Averaging)"),
                    ("fedmedian", "联邦中位数 (Federated Median)"),
                    ("buliyan", "Bulyan"),
                    ("krum", "Krum"),
                    ("qfedavg", "Q-FedAvg (Quantile-FedAvg)"),
                    (
                        "dp_adaptive_clipping",
                        "差分隐私自适应梯度裁剪 (DP Adaptive Clipping)",
                    ),
                    ("dp_fixed_clipping", "差分隐私固定梯度裁剪 (DP Fixed Clipping)"),
                    (
                        "dpfedavg_adaptive",
                        "差分隐私联邦平均自适应裁剪 (DPFedAvg Adaptive)",
                    ),
                    ("dpfedavg_fixed", "差分隐私联邦平均固定裁剪 (DPFedAvg Fixed)"),
                    ("fedavg_android", "联邦平均 (Android 优化)"),
                    ("fedxgb_bagging", "联邦 XGBoost Bagging"),
                    ("fedxgb_cyclic", "联邦 XGBoost 循环"),
                    ("fedxgb_nn_avg", "联邦 XGBoost 神经网络平均"),
                    ("fedyogi", "联邦 Yogi (Federated Yogi)"),
                ],
                db_index=True,
                default="fedavg",
                max_length=50,
                verbose_name="聚合方式",
            ),
        ),
        migrations.AlterField(
            model_name="federatedtask",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="federatedtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
