# Generated by Django 5.0.6 on 2025-07-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0009_regionnode_edgenode"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="edgenode",
            unique_together={("device_id", "region")},
        ),
        migrations.AddField(
            model_name="edgenode",
            name="device_context",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="设备上下文"
            ),
        ),
        migrations.RemoveField(
            model_name="edgenode",
            name="port",
        ),
    ]
