# Generated by Django 5.0.6 on 2025-07-18 07:11

import django.db.models.deletion
import timescale.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0010_alter_edgenode_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="请求方法"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="请求路径"
                    ),
                ),
                (
                    "body",
                    models.TextField(blank=True, null=True, verbose_name="请求体"),
                ),
                (
                    "response_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="响应状态码"
                    ),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, null=True, verbose_name="响应体"),
                ),
                (
                    "created_at",
                    timescale.db.models.fields.TimescaleDateTimeField(
                        auto_now_add=True, interval="1 day", verbose_name="创建时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "ordering": ["-id"],
            },
        ),
    ]
