# Generated by Django 5.0.6 on 2025-07-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0011_operationlog"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="operationlog",
            table_comment="操作日志表",
        ),
        migrations.AlterModelTable(
            name="operationlog",
            table="operation_log",
        ),
    ]
