# Generated by Django 5.0.6 on 2025-07-18 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0012_alter_operationlog_table_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="federatedtask",
            name="model_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learn_management.modelversion",
                verbose_name="模型版本",
            ),
        ),
        migrations.AddField(
            model_name="federatedtask",
            name="region_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learn_management.regionnode",
                verbose_name="区域服务器",
            ),
        ),
        migrations.AlterField(
            model_name="federatedtask",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="federatedtask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
