# Generated by Django 5.0.6 on 2025-07-18 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0013_federatedtask_model_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="federatedtask",
            name="model_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="learn_management.modelinfo",
                verbose_name="模型信息",
            ),
        ),
    ]
