# Generated by Django 5.0.6 on 2025-07-22 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0014_federatedtask_model_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="edgenode",
            old_name="region",
            new_name="region_node",
        ),
        migrations.AlterUniqueTogether(
            name="edgenode",
            unique_together={("device_id", "region_node")},
        ),
        migrations.CreateModel(
            name="TrainingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="设备ID"
                    ),
                ),
                (
                    "device_context",
                    models.JSONField(default=dict, verbose_name="设备上下文"),
                ),
                (
                    "training_context",
                    models.JSONField(default=dict, verbose_name="训练上下文"),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="训练时长（秒）"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("canceled", "Canceled"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "edge_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn_management.edgenode",
                        verbose_name="边缘设备",
                    ),
                ),
                (
                    "federated_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn_management.federatedtask",
                        verbose_name="联邦任务",
                    ),
                ),
                (
                    "model_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn_management.modelinfo",
                        verbose_name="模型信息",
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn_management.modelversion",
                        verbose_name="模型版本",
                    ),
                ),
                (
                    "region_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learn_management.regionnode",
                        verbose_name="区域节点",
                    ),
                ),
            ],
            options={
                "verbose_name": "训练记录",
                "db_table": "training_record",
                "db_table_comment": "训练记录表",
                "ordering": ["-id"],
                "unique_together": {
                    (
                        "device_id",
                        "edge_node",
                        "federated_task",
                        "model_info",
                        "model_version",
                        "region_node",
                    )
                },
            },
        ),
    ]
