# Generated by Django 5.0.6 on 2025-07-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0015_rename_region_edgenode_region_node_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="federatedtask",
            name="participation_rate",
            field=models.FloatField(default=0.5, verbose_name="参与率"),
        ),
    ]
