# Generated by Django 5.0.6 on 2025-09-26 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0016_federatedtask_participation_rate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="federatedtask",
            name="participation_rate",
            field=models.IntegerField(default=50, verbose_name="参与率"),
        ),
        migrations.CreateModel(
            name="ModelInferenceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.JSONField(verbose_name="输入数据")),
                (
                    "output_data",
                    models.JSONField(blank=True, null=True, verbose_name="输出数据"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_inference_logs_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "edge_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_logs",
                        to="learn_management.edgenode",
                        verbose_name="边缘设备",
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_logs",
                        to="learn_management.modelversion",
                        verbose_name="模型版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型推理日志",
                "db_table": "model_inference_log",
                "db_table_comment": "模型推理日志表",
                "ordering": ["-id"],
            },
        ),
    ]
