# Generated by Django 5.0.6 on 2025-12-10 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learn_management", "0017_alter_federatedtask_participation_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FederatedTrainingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="设备ID",
                    ),
                ),
                (
                    "round",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="训练轮次"
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("train", "训练阶段"),
                            ("upload", "上传阶段"),
                            ("aggregate", "聚合阶段"),
                            ("evaluate", "评估阶段"),
                            ("system", "系统事件"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=20,
                        verbose_name="日志阶段",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "DEBUG"),
                            ("INFO", "INFO"),
                            ("WARNING", "WARNING"),
                            ("ERROR", "ERROR"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=10,
                        verbose_name="日志级别",
                    ),
                ),
                (
                    "loss",
                    models.FloatField(blank=True, null=True, verbose_name="损失值"),
                ),
                (
                    "accuracy",
                    models.FloatField(blank=True, null=True, verbose_name="准确率"),
                ),
                (
                    "num_examples",
                    models.IntegerField(blank=True, null=True, verbose_name="样本数量"),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="其他指标"
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="日志消息"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "log_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="日志时间戳"
                    ),
                ),
                (
                    "duration",
                    models.FloatField(blank=True, null=True, verbose_name="耗时（秒）"),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="扩展数据"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "region_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_logs",
                        to="learn_management.regionnode",
                        verbose_name="区域节点",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_logs",
                        to="learn_management.federatedtask",
                        verbose_name="联邦任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "训练日志",
                "verbose_name_plural": "训练日志",
                "db_table": "federated_training_log",
                "db_table_comment": "联邦学习训练日志表",
                "ordering": ["-log_timestamp", "-id"],
                "indexes": [
                    models.Index(
                        fields=["task", "round", "phase"],
                        name="federated_t_task_id_50b54e_idx",
                    ),
                    models.Index(
                        fields=["device_id", "round"],
                        name="federated_t_device__5cfa65_idx",
                    ),
                    models.Index(
                        fields=["level", "log_timestamp"],
                        name="federated_t_level_8cfa0a_idx",
                    ),
                ],
            },
        ),
    ]
