export { default as Nav } from './Nav'
export { default as Hero } from './Hero'
export { default as QuickStart } from './QuickStart'
export { default as Features } from './Features'
export { default as Footer } from './Footer'
