# Generated by Django 5.0.6 on 2024-05-14 06:01

import os
import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def insert_initial_user_data(apps, schema_editor):
    User = apps.get_model("user", "AuthUserExtend")
    user_list = [
        User(
            name="superadmin",
            mobile="13012341234",
            email="superadmin@admin.com",
            password=make_password("superadmin"),
            is_superuser=True,
            is_admin=True,
        ),
        User(
            name="admin",
            mobile="13012341235",
            email="admin@admin.com",
            password=make_password("admin"),
            is_superuser=False,
            is_admin=True,
        ),
    ]
    User.objects.bulk_create(user_list)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthUserExtend",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="手机"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="邮箱"
                    ),
                ),
                ("password", models.CharField(max_length=100, verbose_name="密码")),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="超级管理员"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="管理员"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近登录时间"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户信息表",
                "db_table": "auth_user_extend",
                "db_table_comment": "用户信息表",
                "ordering": ["id"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name_en",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="权限英文名称"
                    ),
                ),
                (
                    "name_zh",
                    models.CharField(max_length=80, verbose_name="权限中文名称"),
                ),
                (
                    "parent",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="父级权限ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "权限表",
                "db_table": "permission",
                "db_table_comment": "权限表",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="角色名"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "角色表",
                "db_table": "role",
                "db_table_comment": "角色表",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.permission",
                        verbose_name="权限ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission",
                        to="user.role",
                        verbose_name="角色ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色权限关联表",
                "db_table": "role_permission",
                "db_table_comment": "角色权限关联表",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.role",
                        verbose_name="角色ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户角色关联表",
                "db_table": "user_role",
                "db_table_comment": "用户角色关联表",
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(insert_initial_user_data),
    ]
